spring:
  application:
    name: smart-news-tracker
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
server:
  port: ${SERVER_PORT}
  error:
    include-message: always
    include-binding-errors: always
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 3600000 # 1 hour
      refresh-token:
        expiration: 604800000 #7 days
  base-url: ${SERVER_BASE_URL}:${server.port}
news:
  api:
    url: "https://newsapi.org/v2"
    api-key: ${NEWS_API_KEY}
springdoc:
  swagger-ui:
    tagsSorter: alpha