spring:
  application:
    name: rest-api-springboot
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
  mail:
    host: localhost
    port: 1025
    username: ${DEVMAIL_USERNAME}
    password: ${DEVMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
application:
  security:
    jwt:
      secret-key: 6e3f9b5a4d8e7f2a1c9b0d6e7f3a2b9c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8
      expiration: 3600000 # 1 hour
      refresh-token:
        expiration: 604800000 #7 days
news:
  api:
    url: "https://newsapi.org/v2"
    api-key: ${NEWS_API_KEY}

springdoc:
  swagger-ui:
    tagsSorter: alpha