spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: never
logging:
  level:
    root: ERROR
    dev.kauanmocelin.springbootrestapi.*: ERROR